[package]
name = "boubo_trace"
authors = ["Roman Táborský"]
description = "Tool to trace and save syscalls from specified program"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-or-later"

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.23", features = ["derive"] }
elf = "0.7.4"
env_logger = "0.11.5"
libc = "0.2.158"
log = "0.4"
nix = { version = "0.29.0", features = ["ptrace", "uio", "fs", "sched", "socket", "net"] }
serde = { version = "1.0.210", features = ["derive"]}
serde_json = "1.0.128"
spawn-ptrace = "0.1.2"
strum = { version = "0.26.3", features = ["derive"]}
thiserror = "1.0.64"

[dev-dependencies]
insta = { version = "1.41.1", features = ["glob", "json"] }

[profile.dev.package]
insta.opt-level = 3
