[package]
name = "tracer"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
env_logger = "0.11.5"
libc = "0.2.158"
log = "0.4"
nix = { version = "0.29.0", features = ["ptrace", "uio"] }
spawn-ptrace = "0.1.2"
strum = { version = "0.26.3", features = ["derive"]}
