[package]
name = "tracer"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"

[dependencies]
anyhow = "1.0.86"
elf = "0.7.4"
env_logger = "0.11.5"
libc = "0.2.158"
log = "0.4"
nix = { version = "0.29.0", features = ["ptrace", "uio"] }
serde = { version = "1.0.210", features = ["derive"]}
serde_json = "1.0.128"
spawn-ptrace = "0.1.2"
strum = { version = "0.26.3", features = ["derive"]}
thiserror = "1.0.64"

[build-dependencies]
cc = "1.1.37"

[dev-dependencies]
cc = "1.1.37"
insta = { version = "1.41.1", features = ["glob", "json"] }

[profile.dev.package]
insta.opt-level = 3
similar.opt-level = 3
